version: "3.5"
        
services:
    jenkins:
        container_name: jenkins
        image: devops_jenkins
        ports:
            - "8081:8080"
        volumes:
            - .\docker_volumes\jenkins:/home/jenkins # Allows to write .ssh/known_hosts
            - .\docker_volumes\jenkins_home:/var/jenkins_home
            - .\docker_volumes\jenkins_socket/:/var/run/docker.sock # Jenkins allowed to start/stop containers
            - .\docker_volumes\jenkins_git_repo:/home/jenkins_git_repo
            
    sonarqube:
        container_name: sonarqube
        image: sonarqube:lts
        ports:
            - "8082:9000"
        volumes:
            - .\docker_volumes\sonarqube_conf:/opt/sonarqube/conf
            - .\docker_volumes\sonarqube_data:/opt/sonarqube/data
            - .\docker_volumes\sonarqube_extensions:/opt/sonarqube/extensions
            - .\docker_volumes\sonarqube_logs:/opt/sonarqube/logs
            - .\docker_volumes\sonarqube_temp:/opt/sonarqube/temp
            