version: "3.5"
        
services:
    jenkinsdevoss:
        container_name: jenkinsdevoss
        environment:
            - PLUGINS_FORCE_UPGRADE=true # Enforce upgrade of native plugins at startup
        image: devops_jenkins
        ports:
            - "8081:8080"
        dns_search:
          - jenkins.devossteam.com  
        environment:
            external_url:
                "http://jenkins.devossteam.com/"
        volumes:
            - .\docker_volumes\jenkins:/home/jenkins # Allows to write .ssh/known_hosts
            - .\docker_volumes\jenkins_home:/var/jenkins_home
            - .\docker_volumes\jenkins_socket/:/var/run/docker.sock # Jenkins allowed to start/stop containers
            - .\docker_volumes\project_git_repo\app\back:/home/project_git_repo/app/back
            - .\docker_volumes\project_git_repo\app\front:/home/project_git_repo/app/front

        networks:
            devossnet:
                ipv4_address: 10.0.0.2
                aliases:
                    - "jenkins.devossteam.com"
    sonarqubedevoss:
        container_name: sonarqubedevoss
        image: sonarqube:lts
        ports:
            - "8082:9000"
        networks:
            devossnet:
                ipv4_address: 10.0.0.3  
                aliases:
                    - "sonar.devossteam.com"
        dns_search:
          - sonar.devossteam.com   
        volumes:
            - .\docker_volumes\sonarqube_conf:/opt/sonarqube/conf
            - .\docker_volumes\project_git_repo\app\back:/home/project_git_repo/app/back
            - .\docker_volumes\project_git_repo\app\front:/home/project_git_repo/app/front
            - .\docker_volumes\sonarqube_postgresql:/var/lib/postgresql
            - .\docker_volumes\sonarqube_extensions:/opt/sonarqube/extensions
            - .\docker_volumes\sonarqube_logs:/opt/sonarqube/logs
            - .\docker_volumes\sonarqube_temp:/opt/sonarqube/temp
    
    app-back-devoss:
        container_name: app-back-devoss
        restart: always
        build: .\docker_volumes\project_git_repo\app\back
        working_dir: /docker_volumes/project_git_repo/app/back
        ports:
            - "8008:8008"
        environment:
            - DSERVER.PORT=8008
            - DSPRING.DATASOURCE.URL='jdbc:postgresql://10.0.0.5:5432/postgres'
            - DSPRING.DATASOURCE.USERNAME=postgres
            - DSPRING.DATASOURCE.PASSWORD=postgres1
        volumes:
          - .\docker_volumes\project_git_repo\app\back:/docker_volumes/project_git_repo/app/back
        expose:
          - "8008"
        depends_on:
            - postgres-db-devoss
        command: mvn clean spring-boot:run
        networks:
            devossnet:
                ipv4_address: 10.0.0.6  
                aliases:
                    - "app-back.devossteam.com"
    app-front-devoss:
        container_name: app-front-devoss
        restart: always
        image: app-front-devoss
        ports:
          - "4200:4200"
        volumes:
          - .\docker_volumes\project_git_repo\app\front:/docker_volumes/project_git_repo/app/front
        expose:
          - "4200"
        depends_on:
            - app-back-devoss
          
        networks:
            devossnet:
                ipv4_address: 10.0.0.7  
                aliases:
                    - "app-front.devossteam.com"
    
    postgres-db-devoss:
        container_name: postgres-db-devoss
        image: postgres:latest
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres1
        ports:
          - "6000:5432"
        networks:
            devossnet:
                ipv4_address: 10.0.0.5
                aliases:
                    - "postgres-db.devossteam.com"
        dns_search:
          - postgres-db.devossteam.com        
        volumes:
            - .\docker_volumes\postgres_sock:/var/run/postgres/postgres.sock
            - .\docker_volumes\postgres_database:/var/lib/postgresql/data
    nginxserverdevoss:
        container_name: nginxserverdevoss
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .\docker_volumes\project_git_repo\nginx\conf.d:/etc/nginx/conf.d
        networks:
            devossnet:
                ipv4_address: 10.0.0.4  
                aliases:
                    - "nginxserver.devossteam.com"
    
networks:
    devossnet:
        name: devossnet
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.1/16
                  gateway: 10.0.0.1 
