pipeline {
    agent any
    
    triggers {
      pollSCM ''
    }

    stages {
        stage('SonarQube analysis') {
            withSonarQubeEnv(credentialsId: 'f225455e-ea59-40fa-8af7-08176e86507a', installationName: 'My SonarQube Server') 
            {
                // You can override the credential to be used
                sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
            }
        }
        stage('Iniciando') {
            steps {
                echo 'Inicio'
            }
        }
        stage('Procesando') {
            steps {
                echo 'Proceso'
            }
        }
        stage('Publicando') {
            steps {
                echo 'Publicación'
            }
        }
    }
}